### ISSUE TITLE
(Fix) There is no warning alert before step 4 in Mainnet

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/ico-wizard#398]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Mainnet

### If you were able to create it, what is the URL of your crowdsale?

No URL

### Do you have screenshots showing the problem?

Alert is described here: https://github.com/oraclesorg/ico-wizard/blob/master/src/utils/alerts.js#L96.
It notifies users, how many transactions they should sign and estimated cost. It should appear only for Mainnet. I don't see it.

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

No

---

**Comment by fernandomg** [comment]
@vbaranov 
https://github.com/poanetwork/ico-wizard/blob/9c97971d9db470e88bd2c868a599a541090d235c/src/utils/alerts.js#L89
Is Ok to keep using the `0.16` factor to estimate the gas consumption?

**Comment by igorbarinov** [comment]
what is 0.16?

**Comment by vbaranov** [comment]
This isn't the actual factor already. 
0.16 eth - this is the base estimated price for the creation of 1 tier in mainnet without reserved tokens and without whitelist with the gas price before Byzantium hard fork.
This factor should be recalculated with some gas price. And, I think, here
https://github.com/poanetwork/ico-wizard/blob/9c97971d9db470e88bd2c868a599a541090d235c/src/utils/alerts.js#L89
the proportion should be added for gas price, that user will use for crowdsale creation.

**Comment by fernandomg** [comment]
@vbaranov @igorbarinov the gas consumed by `setReservedTokensListMultiple` and `setReservedTokensListMultiple` will increase while more addresses are added. I've been testing with up to 10 addresses for each one, should I use that value as the most pesimistic? multiply it by some secure factor?  extrapolate it to calculate based on the exact amount of addresses?

**Comment by vbaranov** [comment]
@fernandomg yes, you are right, it'll depend on the number of addresses. 
a) Will it be difficult to calculate price, as:
```
 price = (n * gas_0 + k * gas_to_add_1_address_to_whitelist + m * gas_to_add_1_address_to_reserved_tokens) * user_gas_price
```
where
`gas_0` - gas for creation 1-tier crowdsale without whitelist and reserved tokens,
`n` - number of tiers,
`k` - number of whitelisted addresses for all tiers,
`m` - number of reserved addresses,
`user_gas_price` - gas price, user will use for crowdsale
``
?
b) If yes, let's calculate price, as:
```
 price = n * gas_0 * user_gas_price
```
and add to alert info, how much adding an address to whitelist and reserved tokens list cost
