### ISSUE TITLE
Retry Contract

### ISSUE THREAD

**Issue by madmanjake** [poanetwork/ico-wizard#408]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Mainnet

### If you were able to create it, what is the URL of your crowdsale?

Unable to create

### Do you have screenshots showing the problem?

Yes
![4th contract rejected](https://user-images.githubusercontent.com/34692163/34176401-c708b246-e4cd-11e7-9d60-eab4c74bf565.jpg)
![crowdsale error](https://user-images.githubusercontent.com/34692163/34176402-c71f794a-e4cd-11e7-8743-f5048138e855.jpg)

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

No

three of the contracts went fine but I ran out of ether for the 4th. I quickly sent more over but my 4th contract rejected. How do I now complete it?
---

**Comment by madmanjake** [comment]
Actually it does say User denied transaction signature in the Dev console.

**Comment by igorbarinov** [comment]
If you feel adventurous you could try to continue recovering it manually following this Wiki https://github.com/oraclesorg/ico-wizard/pulls

**Comment by madmanjake** [comment]
Checked out the link and I guess I don't understand it. I'm willing to do any work to get it created but is it too late? Is there a way to run the fourth contract in the compiler? When I try I get an error that "This contract does not implement all functions and thus cannot be created."

**Comment by igorbarinov** [comment]
I see.. ping me on telegram @igorbarinov

**Comment by igorbarinov** [comment]
I'll help you

**Comment by madmanjake** [comment]
Sorry was commuting. I will have to pick this up again tomorrow. I just downloaded telegram. New to both solidarity and github.

**Comment by igorbarinov** [comment]
@madmanjake what's up? please contact me on telegram
