### ISSUE TITLE
(Fix) extend MintedTokenCappedCrowdsaleExt constructor with tier name propoerty

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/ico-wizard#420]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

each network

### If you were able to create it, what is the URL of your crowdsale?

there is no URL

### Do you have screenshots showing the problem?

No. `MintedTokenCappedCrowdsaleExt` constructor is extended with tier name property from this PR https://github.com/poanetwork/ico/pull/10. We should extend it at ICO Wizard side when do deploy.

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

No

---

**Comment by fvictorio** [comment]
@fernandomg please, after fixing this, modify `.gitmodules` to make `submodules/oracles-token-market-net-ico` use a specific commit instead of the master branch. Otherwise, each breaking change in the underlying module can break the wizard.

**Comment by fvictorio** [comment]
Also, please update the URLs of the submodules to use the `poanetwork` organization.
