### ISSUE TITLE
SafeMath library was verified in a different contact address than ICO Wizard

### ISSUE THREAD

**Issue by btcbtq** [poanetwork/ico-wizard#429]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Mainnet

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.oracles.org/crowdsale?addr=0xC6A446Ca27a1F3F80cFc1c0e14Fa12a943aa3974&networkID=1

### Do you have screenshots showing the problem?

There are 2 verified contracts on Etherscan
https://etherscan.io/address/0xf54E5677B1BddF9B552290Be3bA79EAf5AdC53B3#code
https://etherscan.io/address/0xe500629969fecd448cd9b448367645f1ac3c6e06#code

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

No

---

**Comment by vbaranov** [comment]
SafeMath contract has no constructor parameters. Each version of SafeMathLib contract is common for all crowdsales built with ICO Wizard. This is why it has the same code and it is already verified by previous users of ICO Wizard.
