### ISSUE TITLE
(Fix) Custom gas price should allow value less than 1 gwei

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/ico-wizard#437]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Each network

### If you were able to create it, what is the URL of your crowdsale?

No URL

### Do you have screenshots showing the problem?

No. Relates to #393 #430. Custom gas price could be cheaper than 1 gwei for such cheap network as https://core.poa.network.

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

No.

---

**Comment by igorbarinov** [comment]
@vbaranov gasprice in Core is 1gwei or more. Let's close the issue

**Comment by vbaranov** [comment]
https://monosnap.com/file/SljXBjg6FBBszsldxjbU07JpzMeJTX - netstat misled

**Comment by igorbarinov** [comment]
@vbaranov when you have time please check where from  netstat takes this value
- [ ] 500 mwei question
