### ISSUE TITLE
(Fix) Incorrect default start date of crowdsale, if it is created at the start of the day

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/ico-wizard#444]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Each network

### If you were able to create it, what is the URL of your crowdsale?

There is no crowdsale

### Do you have screenshots showing the problem?

![image 2018-01-05 00-28-19](https://user-images.githubusercontent.com/4341812/34585194-ce07d0ba-f1af-11e7-95e1-5367bea8c815.png)

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

No

---

**Comment by rstormsf** [comment]
I believe it's related to timezones. How do expect reading your localtimezone?

**Comment by vbaranov** [comment]
There is definitely a bug in this function:
https://github.com/poanetwork/ico-wizard/blob/master/src/components/stepThree/utils.js#L1
because I expect my local time + 5 minutes in this field, and it displays correct local time, when I try to create crowdsale not at the start of the day.

**Comment by rstormsf** [comment]
@vbaranov why not use moment.js ? that can take of those things without much of calculations?

**Comment by vbaranov** [comment]
Good idea
