### ISSUE TITLE
Npm Start, loads localhost:300 with Error

### ISSUE THREAD

**Issue by jacobabiola** [poanetwork/ico-wizard#446]
After i succeeded in following the steps on how to run the ICO-Wizard on MacOs, and i ran the 'Npm Start' command on the terminal and i visited localhost:3000 on the browser i got 

Error: REACT_APP_REGISTRY_ADDRESS env variable is not present

please the attached screenshot of the complete error on my browser.

![screen shot 2018-01-06 at 1 14 42 am](https://user-images.githubusercontent.com/24619534/34633861-46d53bd4-f27f-11e7-818b-4811cb3021ea.png)

**Comment by fernandomg** [comment]
@jacobabiola hello!

Please refer to the tl;dr on this comment https://github.com/poanetwork/ico-wizard/pull/404#issue-282575428

**Comment by vbaranov** [comment]
I've updated wiki with missing step: https://github.com/poanetwork/ico-wizard/wiki/ICO-Wizard-How-to-run#getting-started

**Comment by tcsekhar** [comment]
Even now, after following the steps in the link above, I get the same error message.

**Comment by vbaranov** [comment]
@tcsekhar link above was broken. I fixed the path. Please follow instructions from this link.
