### ISSUE TITLE
(Feature) use gasprice oracle on invest page

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/ico-wizard#449]
Problem:
On invest page, we are using fixed price of 15 Gwei
Solution:
For `Foundation` network use the gasprice oracle with `safe` value

**Comment by vbaranov** [comment]
Reminder to assignee:
After merging https://github.com/poanetwork/ico-wizard/pull/430 the gasprice oracle with safe value is used for each network.

**Comment by igorbarinov** [comment]
@vbaranov gasprice oracle is used only for mainnet.. we don't have oracles for other networks.

**Comment by vbaranov** [comment]
@igorbarinov yes, and this is why I added the reminder to this issue. Now ICO Wizard calculates slow price from oracle (where values are from mainnet) for every network. Is this correct, if, for example, for Core POA we have 1Gwei ?

**Comment by igorbarinov** [comment]
It is not correct. But not a problem.. Maybe it's good to show people how much transaction costs on the foundation network
