### ISSUE TITLE
Npm Start Error display on localhost:300

### ISSUE THREAD

**Issue by jacobabiola** [poanetwork/ico-wizard#452]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Your answer*
Yet to start the wizard on the browser
### If you were able to create it, what is the URL of your crowdsale?

*Your answer*
Not Yet
### Do you have screenshots showing the problem?

*Your answer*
![screen shot 2018-01-06 at 1 14 42 am](https://user-images.githubusercontent.com/24619534/34652361-e2387aec-f3dc-11e7-9d61-2272ec5b2776.png)

### Do you see errors in the dev console? If yes, please include a screenshot
No
(To
 open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

*Your answer*
No
---
Hi,

i get the error on the screenshot above when i type "npm start' on the terminal to start the ICO wizard.

this after installing all the neccessary dependencies as requested by the Read Me file.

what am i missing out?

**Comment by vbaranov** [comment]
Please check https://github.com/poanetwork/ico-wizard/wiki/ICO-Wizard-How-to-run. 
You need to create .env file with registry addresses.
