### ISSUE TITLE
Unable to create crowdsale - undefined NullFinalizeAgent contract address

### ISSUE THREAD

**Issue by yfukata** [poanetwork/ico-wizard#453]
Quick help needed!

If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)
Mainnet

### If you were able to create it, what is the URL of your crowdsale?
Unable to create crowdsale, but files were downloadable. 
The same phenomenon occurred the last time I tried to create a crowdsale, couple hours ago.
When I look into NullFinalizeAgentExt text files, the contract addresses for all tiers were undefined.

### Do you have screenshots showing the problem?

![image](https://user-images.githubusercontent.com/17077914/34652887-b4580f3e-f427-11e7-991d-be739264d077.png)
![image](https://user-images.githubusercontent.com/17077914/34652890-bc34f3ca-f427-11e7-8bf5-d77128fffb78.png)
![image](https://user-images.githubusercontent.com/17077914/34653009-19b20b90-f429-11e7-852e-fe21b050c1bd.png)
![image](https://user-images.githubusercontent.com/17077914/34653015-268280d4-f429-11e7-94c4-e768bd582273.png)
![image](https://user-images.githubusercontent.com/17077914/34653016-2bd6b122-f429-11e7-892a-2b2bd33159f6.png)
![image](https://user-images.githubusercontent.com/17077914/34653522-22c26c46-f430-11e7-9a16-89a99c94dc99.png)

### Do you see errors in the dev console? If yes, please include a screenshot

Sorry, perhaps because I proceeded to "CONTINUE," I think I missed a chance to take a screenshot.
If downloaded files are needed, please let me know.

---

Thank you for your help!

**Comment by yfukata** [comment]
Same failure occurred again; this time I captured a screenshot : 

![error](https://user-images.githubusercontent.com/17077914/34655766-975c7a52-f452-11e7-8f6c-fc77e20ab716.jpg)

**Comment by vbaranov** [comment]
Relates to #457
