### ISSUE TITLE
Could Not Get to Crowdsale Page

### ISSUE THREAD

**Issue by kevinlwalker** [poanetwork/ico-wizard#456]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Mainnet

### If you were able to create it, what is the URL of your crowdsale?

Not able to create it a crowdsale. The contract was created, but I am unable to fully complete to contract and get to the crowdsale page. 

https://etherscan.io/address/0x83a988c20483fe4ee7d32c9f765a624d5352d223

### Do you have screenshots showing the problem?

No. 

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

No errors seen.

---

**Comment by vbaranov** [comment]
As I can see, you've signed only the first transaction. Please check wiki about number of transactions, you should sign with wizard, and estimated timing: https://github.com/poanetwork/ico-wizard/wiki/ICO-Wizard-Deployment-Time-and-Gas
