### ISSUE TITLE
Fail to create crowdsale contract address

### ISSUE THREAD

**Issue by yfukata** [poanetwork/ico-wizard#457]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)
Mainnet 
 Successful in Kovan, but fails when using Mainnet

### If you were able to create it, what is the URL of your crowdsale?
No; it did not create crowdsale page / address (only token address)

### Do you have screenshots showing the problem?

Comparison of files created with Kovan(successful) and Mainnet(Failed), using same setting parameters.
![image](https://user-images.githubusercontent.com/17077914/34660248-1b19265c-f484-11e7-8214-4305c07f5661.png)

![image](https://user-images.githubusercontent.com/17077914/34660334-d5ef97d6-f484-11e7-9caf-207701c5d968.png)

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

*Your answer*

---

Thank you for your help!

**Comment by vbaranov** [comment]
Relates to https://github.com/poanetwork/ico-wizard/pull/404#issuecomment-355978973
The contracts registry address is added for Mainnet. Thank you for posting!

**Comment by yfukata** [comment]
Thank you for looking into the issue.
Since the issue was closed, I tried creating crowdsale again in Mainnet; however, it failed again - looks similar like similar error , but there were 2 errors shown instead on 1. 
Was I too early to use? or should I create a new issue?
I'm in a hurry to launch a crowdsale using your web, and I would appreciate your quick help!!!

**Comment by vbaranov** [comment]
Error on the 2nd screenshot is not related to the ICO Wizard. It the issue with one of your Chrome extensions.
