### ISSUE TITLE
Issue editing early participant whitelist for muti-tiered crowdsale

### ISSUE THREAD

**Issue by skydudie** [poanetwork/ico-wizard#458]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Ropstern Testnet

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.oracles.org/crowdsale?addr=0x2335D385679F01b7Ce8202d6Df1c0554199557fd&networkID=3

I’m having problems adding wallet addresses to the participant whitelist after the crowdsale has started.
The crowdsale is set up with 4 tiers, each initialised with a blank participant whitelist.

Following the instructions on the wiki (https://github.com/poanetwork/ico-wizard/wiki/Add-address-to-white-list) on how to add participants to the whitelist does not work.
The wallet addresses get added to the list as I can see that the whitelistedParticipantLength number increase, I can also see that the address is added through the earlyParticipantWhitelist method but the address is still unable to buy tokens as the transaction fails.

The strange thing is, the instructions only work on the final tier of the crowdsale, the previous tiers will not accept any purchases from any wallets, but the last tier will accept those wallets that are added to its whitelist.

I did the exact same steps for all the tiers, but only the last tier accepts payments from the added addresses.

**Comment by vbaranov** [comment]
As I can see from your test crowdsale, you didn't add a whitelist for every tier. For example, your 2nd tier (0x8be099b1dfed640790d3c5d2e23eec3ce71fdaca) has no whitelist. And your tiers are very short in a time interval. Are you sure, that when you tried to buy tokens, you were on the same tier in time, where you have added whitelist participants? If you want your whitelist participant can buy at every tier, you should add it to every tier (if you do it manually).

**Comment by skydudie** [comment]
Yes, I didn't add a whitelist for every tier as I want to separate which wallet address can buy at which tier.
The reason why the tier timings are so short is that this was the 8th test I was running, I'm certain that I was on the correct tier when I was buying tokens.

When I launched the crowdsale all the tiers have empty whitelist, I then manually added addresses to the different tier's whitelist following the instructions in the wiki. 
The issue is that even though an address has been added to the whitelist for a certain tier, that address is still unable to purchase any tokens from that tier.

The only time this functionality worked was for the last tier.

**Comment by vbaranov** [comment]
Thank you for the detailed explanation.

This is because whitelists in ICO Wizard strategy are inherited* in the tiers. And if you need to make it work manually, you should add the same whitelist object to the next tiers too.

*it means, that if an address is whitelisted in the previous tier, it can buy on the next tiers too provided that the cap (hard and individual) was not redeemed earlier.

I've updated the wiki post https://github.com/poanetwork/ico-wizard/wiki/Add-address-to-white-list 

>*Note*: White list in the ICO Wizard strategy is inherited. So, If you need to setup white list for multiple tiers crowdsale manually, you should add the same whitelist object for all next tiers too. 
For example, you have 4-tiers crowdsale. You have added address *A* to the 2nd tier. Then you need to add it to the 3d and the 4th tiers too.

**Comment by skydudie** [comment]
Great! It works now, thank you!
