### ISSUE TITLE
Unable to proceed to Step 5 "Crowdsale Data is Empty there is nothing to Deploy"

### ISSUE THREAD

**Issue by KaayaTech** [poanetwork/ico-wizard#461]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)
Mainnet
*Your answer*

### If you were able to create it, what is the URL of your crowdsale?
No. I was able to go to Step 4 and download the zip file with the full contract code.Two contracts got published in the etherscan (one for around 11 dollars and another for around 108 dollars).
*Your answer*

### Do you have screenshots showing the problem?
Yes
![issuewithicowizard](https://user-images.githubusercontent.com/35234088/34685377-24021112-f4ce-11e7-851b-0be9b3936c0c.png)

*Your answer*

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)
No. Log is attached.
[wizard.oracles.org-1515435540918.log](https://github.com/poanetwork/ico-wizard/files/1612571/wizard.oracles.org-1515435540918.log)

*Your answer*

---

**Comment by vbaranov** [comment]
@KaayaTech did you refresh the page before getting this error?

**Comment by vbaranov** [comment]
Could you describe in details what was before downloading? 
How many transactions did you sign? 
Could you describe, what happened, when you signed the last one?
It will help us to reproduce. Thanks in advance.

**Comment by KaayaTech** [comment]
I signed two transactions. After I signed the second transaction, the purple POA splash screen disappeared and I was able to download 16 files icowizard_Mainnet_.zip. 
How many was I supposed to get? ALso what is the estimated cost of having different tiers? 
Currently there is no information available on these, the first transaction costed $10, second one ~$100, how much more are the remaining transactions going to cost?

**Comment by KaayaTech** [comment]
Initially I was doing some transactions using the default safe gas limit. Turns out that safe limit is actually not correct, so my contracts were failing. Then I added $10 to get the contract published, but after the first contract was published, it asked for $100 more for second contract. Since I didn't have that much, the contract failed. So now I put more money into the wallent and created everything from scratch and published the first contract for $10 and the second contract for $100 and was hoping to get the ICO published.

**Comment by KaayaTech** [comment]
@vbaranov Is there any ETA for when this might be resolved. I really appreciate your quick response and hope I can use this platform to launch our ICO.

**Comment by yfukata** [comment]
@vbaranov Hi, sorry to cut in.  I am also in a hurry too, to launch an ICO.  Do you think it's possible to solve the problem, perhaps today?  Earlier today, you closed my issue #457; however, it still fails to create a crowdsale on mainnet.  It works fine in Kovan network, but always fails in mainnet - I've already spent near 10ETHs...
Is there any special way to create a crowdsale, asap?

**Comment by vbaranov** [comment]
You can learn about of amount of transactions to be deployed for a 1-tier contract here https://github.com/poanetwork/ico-wizard/wiki/ICO-Wizard-Deployment-Time-and-Gas. Also, you can find here the estimation of cost. Estimation was done for the gas price less than or equal 5 Gwei. You can recalculate it for the current price of Ether and gas price you'll choose.

As for the steps to minimize risks with mainnet deployment:
1. We have already added dynamic gas price calculation for safe/normal/fast options https://github.com/poanetwork/ico-wizard/pull/430
2. please wait for the completion of updating web3 to the latest version https://github.com/poanetwork/web3.js/issues/1. ETA: during the day.

**Comment by yfukata** [comment]
@vbaranov Thank you very much for your quick support.  I really appreciate it.  I'll be looking forward to hearing from you soon.

**Comment by KaayaTech** [comment]
@vbaranov Thank you for the quick response. Looking forward to hearing from you as I am also trying to launch the ICO by today lik @yfukata

**Comment by KaayaTech** [comment]
Also will I get my money back on these two transactions? Let me know how to go about it.

**Comment by yfukata** [comment]
@KaayaTech refund policy was on wiki: 
https://github.com/poanetwork/ico-wizard/wiki/ICO-Wizard-Refund-Policy

**Comment by igorbarinov** [comment]
@KaayaTech for the refund please write to info@poa.network and mention you txs, the amount you lost and your account.

**Comment by yfukata** [comment]
@vbaranov  Hi, I'm sorry to disturb your development, but how are you doing with the bug-fix? Do you have an approximate time of when I'll be able to use it?  I hope it's ready within couple hours....

**Comment by KaayaTech** [comment]
@vbaranov Any updates? Can you provide a new ETA? Is there a way I can give you the details and you can create the crowdsale for me? I really need it done by today? All help much appreciated.

**Comment by vbaranov** [comment]
https://github.com/poanetwork/ico-wizard/pull/474

ICO Wizard on Mainnet is down for maintenance. For updates, please check our [gitter](https://gitter.im/poanetwork/ico-wizard)

**Comment by vbaranov** [comment]
Creation on the mainnet is opened and takes ~ 2 hours for now and you shouldn't refresh the page until the wizard will end deployment process. #476
