### ISSUE TITLE
Having problems getting past part 4, publish - ICO wizard

### ISSUE THREAD

**Issue by Bl4nkSlate** [poanetwork/ico-wizard#466]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*I used the Mainnet*

### If you were able to create it, what is the URL of your crowdsale?

*I have only the contract address which isn't connected to anything now.
0xc5387da78e589b62d7acfb49cebb2ca4e85c4b4b1950a467dd57f680b4269cae*

### Do you have screenshots showing the problem?

*Your answer*

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

*Your answer*
Yes, but it doesn't show anything with an error.
---

I've been trying to create a token in limited amount to start an initial tier of funding, but I cannot get past the publish on stage 4. The first attempts I was stuck on the purple page loading and assuming my browser froze, refreshed only for it to say to start again leaving this chain (0x110b598e161493323208ac29d6c771a85b6d2057) not connected to anything.
The last try just gave the start again error of no data even when it actually loaded to the page and had info in it.

**Comment by igorbarinov** [comment]
We can't help you if you refreshed the page. At the moment, the wizard doesn't support page refresh due to client-side architecture.

**Comment by Bl4nkSlate** [comment]
The page refresh was the first time. The last time I tried the page gave the error when I clicked to continue past stage 4.

**Comment by igorbarinov** [comment]
Which error? Do you have a log from Chrome console or screenshot?

**Comment by Bl4nkSlate** [comment]
No I don't have those. I only downloaded the file which saves into .zip. 
I still don't know whats triggering the error.

**Comment by igorbarinov** [comment]
me either, unfortunately...
we don't have a server-side backend for the app 

would you mind to test it on a testnet?

**Comment by Bl4nkSlate** [comment]
Okay, does that use ether?

**Comment by igorbarinov** [comment]
Test nets usually use some form of ether but you can get it for free

to use our test network you can deploy your code here
https://faucet-sokol.herokuapp.com/
explorer is very limited now but you could see transactions here
https://sokol-explorer.poa.network/
RPC for metamask is https://sokol.poa.network
Instruction how to connect network to MM https://github.com/poanetwork/wiki/wiki/POA-Network-on-MetaMask

You can google for Kovan faucet and explorer
