### ISSUE TITLE
Clicked "publish" at end of crowdsale setup(stage 3), still on "loading" screen which displays POA Network

### ISSUE THREAD

**Issue by JRS2022** [poanetwork/ico-wizard#469]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

If you mean MetaMask, its the Main Net

### If you were able to create it, what is the URL of your crowdsale?

Not created, i see all the coding in the background but nothing after "Crowdsale Contract ABI"

### Do you have screenshots showing the problem?

i will post here, i hope it loads. I pasted it.
![image](https://user-images.githubusercontent.com/35255825/34713219-8a2a95d0-f560-11e7-9573-5038f3a0d79d.png)

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

i dont know how to check for errors. but i have opened the console via F12.

---

**Comment by JRS2022** [comment]
should i post another screenshot of the dev console view?

**Comment by JRS2022** [comment]
![image](https://user-images.githubusercontent.com/35255825/34713620-cf20aed0-f561-11e7-99b9-69df7ad2cfb1.png)

**Comment by vbaranov** [comment]
There is no errors in dev console. You should wait MetaMask windows for sending of transactions

**Comment by JRS2022** [comment]
okay. its been approximately 30 minutes. ill leave it open and see what happens. thanks. will update again if nothing after a few hours.

**Comment by JRS2022** [comment]
does it matter that theres an erc20 token with the same 3 digit acronym?

**Comment by vbaranov** [comment]
It doesn't matter, if you have successfully passed the validation in the previous steps.
If you haven't signed any transaction yet, I'd recommend you to restart the wizard. If you have already signed some of the transactions, you should wait for the response (if you restart in this case, you'll lose all progress and ether for already sent transactions).
Also, I'd recommend starting the whole process on the test network first. For example, https://github.com/poanetwork/ico-wizard/issues/466#issuecomment-356164877

**Comment by JRS2022** [comment]
nothing has been signed. it didnt even ask me to confirm the number of transactions that would take place. yes i will just restart it. thanks

**Comment by vbaranov** [comment]
Creation on the mainnet takes ~ 2 hours for now and you shouldn't refresh the page untill the wizard will end deployment process.
