### ISSUE TITLE
Crowdsale parts are empty after accepting of the transaction to publish.

### ISSUE THREAD

**Issue by JRS2022** [poanetwork/ico-wizard#471]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Mainnet

### If you were able to create it, what is the URL of your crowdsale?

it didnt create.

### Do you have screenshots showing the problem?

all crowdsale parameters were left blank after i submitted the transaction on mainnet metamask.
![image](https://user-images.githubusercontent.com/35255825/34727609-73d04cf8-f592-11e7-8b17-eba843dbd33f.png)

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

i will post it here. 1 error displayed.
![image](https://user-images.githubusercontent.com/35255825/34727676-9f4ba2ec-f592-11e7-8622-2aa04eaad8df.png)

---

**Comment by vbaranov** [comment]
@JRS2022 could you check, if your transaction still in pending state? You can click to it in MetaMask. It will forward you to etherscan page. I believe it is still in pending state, because of problems on Ethereum mainnet side.

**Comment by JRS2022** [comment]
yes its still pending.

**Comment by JRS2022** [comment]
will the crowdsale sections auto fill when its confirmed on mainnet?

**Comment by vbaranov** [comment]
Unfortunately, no.

We are gonna to close mainnet for maintenance.
We depend on this issue https://github.com/ethereum/web3.js/issues/1255 - it is what actually in your screenshot.

**Comment by JRS2022** [comment]
Okay. So I will need to fill out the form again with the same parameters tomorrow and hope it works this time?Will the contract be published and will I be charged?


Sent from Yahoo Mail for iPhone


On Wednesday, January 10, 2018, 00:28, Victor Baranov <notifications@github.com> wrote:


Unfortunately, no.

We are gonna to close mainnet for maintenance.
We depend on this issue ethereum/web3.js#1255 - it is what actually in your screenshot.

**Comment by JRS2022** [comment]
ok, so shall i try again?

**Comment by vbaranov** [comment]
https://github.com/poanetwork/ico-wizard/pull/474

ICO Wizard on Mainnet is down for maintenance. For updates, please check our [gitter](https://gitter.im/poanetwork/ico-wizard)

**Comment by vbaranov** [comment]
Crowdsale creation is enabled in Mainnet now https://github.com/poanetwork/ico-wizard/pull/476
