### ISSUE TITLE
Config.js 

### ISSUE THREAD

**Issue by jacobabiola** [poanetwork/ico-wizard#475]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Your answer*
Localhost:8545
### If you were able to create it, what is the URL of your crowdsale?

*Your answer*
on a localhost
### Do you have screenshots showing the problem?

*Your answer*
![screen shot 2018-01-10 at 11 11 19 am](https://user-images.githubusercontent.com/24619534/34767058-40227efc-f5f7-11e7-82d7-14d7892c98bd.png)

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

*Your answer*
No error message
---

Please whats the correct ICOconfig on a local host?

**Comment by vbaranov** [comment]
Please check wiki: https://github.com/poanetwork/ico-wizard/wiki/ICO-Wizard-ICO-Configuration.
You should put ID of the network you connect locally in `networkID` prop. IDs of public networks are in the wiki post.
