### ISSUE TITLE
Getting ICO WIzard on Mainnet down for maintenance from past 2 days.

### ISSUE THREAD

**Issue by KaayaTech** [poanetwork/ico-wizard#477]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Mainnet

### If you were able to create it, what is the URL of your crowdsale?

No

### Do you have screenshots showing the problem?
Yes
![ico wizard on mainnet down for maintainence](https://user-images.githubusercontent.com/35234088/34786742-0423b718-f65b-11e7-89c0-47ea0bea9f0a.png)

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

No

---

**Comment by igorbarinov** [comment]
It's down for the maintenance

**Comment by vbaranov** [comment]
Crowdsale creation is enabled in Mainnet now https://github.com/poanetwork/ico-wizard/pull/476

**Comment by iamdbcooper** [comment]
down again..
