### ISSUE TITLE
Total Token supply

### ISSUE THREAD

**Issue by jacobabiola** [poanetwork/ico-wizard#481]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Your answer*
Sokol on Localhost
### If you were able to create it, what is the URL of your crowdsale?

*Your answer*
Localhost
### Do you have screenshots showing the problem?

*Your answer*
![screen shot 2018-01-11 at 1 42 26 pm](https://user-images.githubusercontent.com/24619534/34826081-724603fc-f6d5-11e7-945a-b406ef948ef8.png)

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

*Your answer*
No
---
i succeeded in getting to the invest page, but when i click on Contribute so that i can buy token with my Metamask balance it does not respond to the click event, nothing changes, then i notice that in the 'Total Supply' section on the page, my token 'WMI is 0' . what could be wrong pls. 

Thanks for your usual support @vbaranov

**Comment by fernandomg** [comment]
hey @jacobabiola!

You don't have the crowdsale `addr` in the url.

Try this (in a new tab):
- Go to main page (http://localhost:3000)
- click on "Choose contract"
- click the on the last item listed and click on `Continue` button
- then click on `Crowdsale page` link (see the screenshot)
![image](https://user-images.githubusercontent.com/3315606/34827097-d74f0e56-f6b7-11e7-94da-f6326ad7fb26.png)
- after that, click on `invest`

the url should be something like: `http://localhost:3000/invest?addr=0xC89Ce4735882C9F0f0FE26686c53074E09B0D550&networkID=12648430

**Comment by jacobabiola** [comment]
Hello @fernandomg , 

Thank you for taking the time.

i followed the steps as requested but when i clink on invest i get the same blank page with no token supply .

see steps in screenshot

![screen shot 2018-01-11 at 2 39 28 pm](https://user-images.githubusercontent.com/24619534/34828385-b65eb07c-f6dd-11e7-807c-2e2adc727d53.png)
![screen shot 2018-01-11 at 2 44 39 pm](https://user-images.githubusercontent.com/24619534/34828492-fd81c9ee-f6dd-11e7-9408-cb1721ff8c9a.png)

**Comment by vbaranov** [comment]
@fernandomg invest page could work without querystring, if parameters of crowdsale (address and networkID) are in the config [file](https://github.com/poanetwork/ico-wizard/blob/master/src/components/Common/config.js).

Anyway, I've just checked with another contract in public network:
```
export const ICOConfig = {
  crowdsaleContractURL: '0xC89Ce4735882C9F0f0FE26686c53074E09B0D550',
  networkID: '3'
};
```
and there is no such issue for me.

@jacobabiola could add some details about contract and network you've tried to setup? It seems it is broken.

**Comment by jacobabiola** [comment]
@fernandomg  here is my config.js file and runing a localhost with test network on Sokol RPC.

And i notice that i have to send money for gas several times (up to 21 times) before the contract page shows up.
![screen shot 2018-01-11 at 3 10 20 pm](https://user-images.githubusercontent.com/24619534/34829740-f9b54ecc-f6e1-11e7-9673-46d7ad863827.png)

**Comment by vbaranov** [comment]
@jacobabiola please update description of the issue with the address of your crowdsale. It is hard to eject it from the screenshot.

**Comment by jacobabiola** [comment]
`// DEMO CONFIG (DO NOT DELETE THIS EXAMPLE):
const networks = {
  mainnet: 1,
  morden: 2,
  ropsten: 3,
  rinkeby: 4,
  kovan: 42,
  sokolPOA: 77,
  corePOA: 99
}
export const ICOConfig = {
  crowdsaleContractURL: '0x8D934015773a94B06002Ec40D5dD438735D6FF27',
  networkID: networks.sokolPOA
};
`

my config.js file .

The rather weird thing is that the crowdsale address does appear on the Crowsale page, so i will not also appear on the Invest page.

Am confused here.

**Comment by vbaranov** [comment]
There is no valid crowdsale in Sokol POA with this address:

![image 2018-01-11 17-46-56](https://user-images.githubusercontent.com/4341812/34831309-aae467d6-f6f7-11e7-8535-0a556f3096f9.png)

**Comment by vbaranov** [comment]
There is no valid crowdsale in Sokol POA with this address:

![image 2018-01-11 17-46-56](https://user-images.githubusercontent.com/4341812/34831431-fe2d83a0-f6f7-11e7-8a9d-d40b6303de2d.png)

**Comment by jacobabiola** [comment]
i have tried several attempts yet does not create crowdsale to the Sokol test network. please my config here 
>// DEMO CONFIG (DO NOT DELETE THIS EXAMPLE):
const networks = {
  mainnet: 1,
  morden: 2,
  ropsten: 3,
  rinkeby: 4,
  kovan: 42,
  sokolPOA: 77,
  corePOA: 99
}
export const ICOConfig = {
  crowdsaleContractURL: '0x8D934015773a94B06002Ec40D5dD438735D6FF27',
  networkID: '77'
};

**Comment by vbaranov** [comment]
Firstly you should create crowdsale with empty config and then add an address of your crowdsale to the config. Config is for investing, not for the creation of crowdsale.

**Comment by jacobabiola** [comment]
@vbaranov it finally worked. Thanks alot. :)

 When do we use the configuration in config.js file? 
i checked the crowd sale in https://wizard.poa.network and its working fine, but i don't get the issued token  into my Metamask wallet when i made a contribution.

**Comment by vbaranov** [comment]
If you were able to successfully buy some tokens, then your config.js works.
Why it is better to use configuration file for your instance is described here: https://github.com/poanetwork/ico-wizard/issues/133
>but i don't get the issued token into my Metamask wallet when i made a contribution.

you should add token address to MetaMask to see it:

![2018-01-12 16 39 45](https://user-images.githubusercontent.com/4341812/34877508-67bdc2d4-f7b7-11e7-8c09-61e998aeb14e.png)
