### ISSUE TITLE
(Update) add to managing sections in wiki how to finalize, manage crowdsale from /manage page

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/ico-wizard#484]
After this PR https://github.com/poanetwork/ico-wizard/pull/431 users are able to manage crowdsale from wizard itself from the `/manage` page. We need to update wiki `Managing the crowdsale` section:
https://github.com/poanetwork/ico-wizard/wiki/Set-Crowdsale-Start-and-End-Time
https://github.com/poanetwork/ico-wizard/wiki/Change-max-cap-for-tier
https://github.com/poanetwork/ico-wizard/wiki/Change-rate
https://github.com/poanetwork/ico-wizard/wiki/Finalize-crowdsale
https://github.com/poanetwork/ico-wizard/wiki/Add-address-to-white-list
with the primary option to manage crowdsale parameters from wizard.

**Comment by fvictorio** [comment]
@vbaranov I added a page documenting how to go the Manage crowdsale page (https://github.com/poanetwork/ico-wizard/wiki/Manage-crowdsale-page). I also added a section to each of the pages you indicated, explaining how to use the Manage crowdsale page to perform that task. Let me know if there's something wrong or missing.

**Comment by vbaranov** [comment]
Thanks, Franco! I'll take a look.

**Comment by vbaranov** [comment]
@fvictorio Looks good to me. The issue could be closed.

**Comment by hashguide** [comment]
are the crowdsale parameters supposed to be modifiable through the `manage` page on the wizard? I have a crowdsale that hasn't started yet and the fields are all grayed out.

**Comment by fernandomg** [comment]
@hashguide did you marked each tier as modifiable? If so, can you share the crowdsale address?

**Comment by hashguide** [comment]
Yes, I have a single tier and marked it as modifiable.
https://wizard.poa.network/manage/0x6bE9358c20533126130D7643DF047F2b14768d0F
sokol network
You are supposed to be able to change the times, supply, rate and add whitelist?

**Comment by fernandomg** [comment]
@hashguide yes, that's a bug on manage screen (#519)

> Also, if the crowdsale hasn't started yet, is the pie timer supposed to show the countdown til the start of crowdsale or always the end of crowdsale? Seems like the countdown should count to the start of it and switch to the end once started.

I agree with the change you propose. @vbaranov what you think? If it's ok, I'll create the issue for it.

**Comment by vbaranov** [comment]
Sounds good. I agree too.

**Comment by hashguide** [comment]
I noticed that I am now able to edit the parameters to one of my crowdsales, reason I wasn't able to with the other 2 is because they have not started yet. Should the parameters be modifiable before the crowdsale has begun? Seems like that would be good to implement in case people want to change rate or supply before crowdsale starts.

**Comment by fernandomg** [comment]
@hashguide indeed, that was what we did here https://github.com/poanetwork/ico-wizard/issues/519

**Comment by hashguide** [comment]
looks good!
