### ISSUE TITLE
How do i build the code to deploy to live server netlify.com

### ISSUE THREAD

**Issue by jacobabiola** [poanetwork/ico-wizard#485]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Your answer*
Sokol
### If you were able to create it, what is the URL of your crowdsale?

*Your answer*
Localhost
### Do you have screenshots showing the problem?

*Your answer*
NO
### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

*Your answer*

---

Please how do i build the ICO wizard source on my localhost for deployment to a hosting server https://www.netlify.com/

?

**Comment by vbaranov** [comment]
Please take a look at our wiki post: https://github.com/poanetwork/ico-wizard/wiki/Deployment-to-Netlify
