### ISSUE TITLE
Building to deploy to Netlify

### ISSUE THREAD

**Issue by jacobabiola** [poanetwork/ico-wizard#489]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Your answer*
Sokol
### If you were able to create it, what is the URL of your crowdsale?

*Your answer*
Localhost
### Do you have screenshots showing the problem?

*Your answer*

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

*Your answer*

---

Please i was trying to build the ICO wizard for production to Netlify server, 
when i run the build command
```
git submodule update --init --recursive --remote && npm run build && cp ./build/index.html ./build/invest.html && cp ./build/index.html ./build/crowdsale.html
```

 i get this error

```
fatal: unable to access 'https://github.com/poanetwork/oracles-combine-solidity/': 
Could not resolve host: github.com Unable to fetch in submodule path 'submodules/oracles-combine-solidity'
```

please someone help. Thank you.

**Comment by igorbarinov** [comment]
@vbaranov please take a look

also, do we need to add `REACT_APP_REGISTRY_ADDRESS` for all networks in the wiki? https://github.com/poanetwork/ico-wizard/wiki/Deployment-to-Netlify

**Comment by vbaranov** [comment]
@igorbarinov I added addresses for all networks.

**Comment by vbaranov** [comment]
@jacobabiola will it work for you with build command: `npm run build` ? Please let us know.

**Comment by jacobabiola** [comment]
npm run build did not work, got this error 

```
npm ERR! path /Users/apple/wiz/node_modules/web3/node_modules/web3-core/node_modules/web3-core-requestmanager/node_modules/web3-providers-ws/node_modules/is-typedarray
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/apple/wiz/node_modules/web3/node_modules/web3-core/node_modules/web3-core-requestmanager/node_modules/web3-providers-ws/node_modules/is-typedarray' -> '/Users/apple/wiz/submodules/oracles-web3-1.0/packages/web3-core-helpers/node_modules/is-typedarray'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2018-01-14T19_21_19_457Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 254
npm ERR! ico_wizard@0.2.0 build: `git submodule update --init --recursive --remote && cd submodules/oracles-combine-solidity && npm install && cd ../../ && npm install && cd submodules/oracles-web3-1.0 && npm install && cd ../../ && npm install submodules/oracles-web3-1.0/packages/web3 && npm run generateFlatSoliditySafeMathLibContract && npm run generateFlatSolidityCrowdsaleNullFinalizeAgentContract && npm run generateFlatSolidityCrowdsaleFinalizeAgentContract && npm run generateFlatSolidityCrowdsaleContract && npm run generateFlatSolidityCrowdsaleTokenContract && npm run generateFlatSolidityCrowdsalePricingStrategyContract && npm run generateFlatSolidityRegistryContract && npm run compileSafeMathLibExtContract && npm run compileCrowdsaleNullFinalizeAgentContract && npm run compileCrowdsaleFinalizeAgentContract && npm run compileCrowdsaleContract && npm run compileCrowdsaleTokenContract && npm run compileCrowdsalePricingStrategyContract && npm run compileRegistryContract && node scripts/build.js && cp ./build/index.html ./build/invest.html && cp ./build/index.html ./build/crowdsale.html`
npm ERR! Exit status 254
npm ERR! 
npm ERR! Failed at the ico_wizard@0.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2018-01-14T19_21_19_576Z-debug.log
```

**Comment by vbaranov** [comment]
@jacobabiola I have successfully deployed ICO Wizard from master branch: https://quizzical-snyder-8f7fd7.netlify.com/ following steps described in wiki: https://github.com/poanetwork/ico-wizard/wiki/Deployment-to-Netlify.

Are you following these steps too?
Which repository are you trying to deploy from? Which branch?

All steps you should define in Netlify UI. You shouldn't start `npm run build` locally

**Comment by jacobabiola** [comment]
i made modification to the ICO wizard code on my localhost,  i want to host my own version of the code to Netlify

**Comment by vbaranov** [comment]
Did you try to upload your local code to your repository and follow the steps from wiki to deploy to Netlify?

**Comment by jacobabiola** [comment]
am work on that. will keep you in the loop. thanks

**Comment by vbaranov** [comment]
@jacobabiola Did it work for you?

**Comment by jacobabiola** [comment]
am finding it difficult to move the files on my localhost to my github account so i can deploy to Netlify.

Am using github desktop application when i move the file to start uploading to my account after a few seconds it automatically change the folder name to Ico-wizard and will ask if i want to commit changes i made to the downloaded repo to poanetwork ico-wizard repository. 

What and trying to do is to upload my own version of the ICO-wizard i modified but it wouldn't go through.

Do you know a way out?

**Comment by vbaranov** [comment]
The simplest solution is to fork our repository, clone forked repository, add your changes to local copy, commit and push to your forked repo. And then you can use your forked repo in Netlify setup. There shouldn't be problem here.

**Comment by jacobabiola** [comment]
Thank you for the support. i will try that approach and let you know.

**Comment by jacobabiola** [comment]
Its been an interesting journey so far on ICO-Wizard, 

I forked the ICO-wizard repo and deployed from my account to Netlify but i get just a blank page after successful deployment on Netlify, see here 

[https://hopeful-stonebraker-4c0c5a.netlify.com](url) 

thank you

**Comment by vbaranov** [comment]
You didn't set `REACT_APP_REGISTRY_ADDRESS` env variable as described in wiki. You can see this error in Chrome developer console.
