### ISSUE TITLE
Release reserved tokens

### ISSUE THREAD

**Issue by dcxblockchain** [poanetwork/ico-wizard#491]
Hi,

I there a way to release reserved token before ico has ended?

Br
Martijn

**Comment by vbaranov** [comment]
If you haven't created crowdsale yet, you can create additional short tier whitelisted only with your address and buy some tokens. Thus, you'll reserve some tokens before crowdsale finalization.

**Comment by dcxblockchain** [comment]
crowdsale is running allready

**Comment by vbaranov** [comment]
If your crowdsale is not whitelisted, or your address is whitelisted, you still can do the same. In this case your users will be able to buy `maxCap - number of tokens you will reserve this way`.
