### ISSUE TITLE
How to change the reserve amount before finalizing the crowdsale?

### ISSUE THREAD

**Issue by ybugroup** [poanetwork/ico-wizard#492]
Is it possible via contract calls/functions to change the reserve amount before calling finalize() for the crowdsale?

If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Ropsten

### If you were able to create it, what is the URL of your crowdsale?

Yes

### Do you have screenshots showing the problem?

N/A

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

N/A

---

**Comment by vbaranov** [comment]
Yes, if your crowdsale was created after this PR merged: https://github.com/poanetwork/ico-wizard/pull/496. How to set reserved tokens manually, please, check our wiki: https://github.com/poanetwork/ico-wizard/wiki/Set-reserved-tokens.
