### ISSUE TITLE
New crowdsale with existing token

### ISSUE THREAD

**Issue by dcxblockchain** [poanetwork/ico-wizard#500]
Hi,

Can i create a new 3 tier crowdsale using an existing token which is created in a previous crowdsale?

Br
Martijn

**Comment by vbaranov** [comment]
Yes, you can, but it is a little bit complicated:
1. you should create a new crowdsale with new sample token (you won't use this token further) with ICO Wizard.
2. you should repeat all deployment steps for your new crowdsale manually: 
- https://github.com/poanetwork/ico-wizard/wiki/Set-mint-agent
- https://github.com/poanetwork/ico-wizard/wiki/Set-release-agent
- https://github.com/poanetwork/ico-wizard/wiki/Transfer-ownership

In each step, where you'll see token, you should use the old token address. Crowdsale contract, Pricing strategy, Finalize Agent are from the new crowdsale. And keep in mind, that the current owner of the previous token is the wallet address, where you planned to collect funds from the 1st crowdsale.

**Comment by dcxblockchain** [comment]
maybe i forgot to mention the previous contract was finalized. This means that in the existing token contract mintingfinished value true has. So i think that its not possible to use a previous token in a new crowdsale. Also the array token cannot be updated in the new contract.... I couldn't get it working anyway....
