### ISSUE TITLE
How to verify contract source code on etherscan

### ISSUE THREAD

**Issue by jacobabiola** [poanetwork/ico-wizard#507]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Your answer*
Kovan
### If you were able to create it, what is the URL of your crowdsale?

*Your answer*

### Do you have screenshots showing the problem?

*Your answer*

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---
How do we verify deployed contract source code on etherscan?

**Comment by vbaranov** [comment]
https://github.com/poanetwork/ico-wizard/wiki/ICO-Wizard-Verifying-Contracts
