### ISSUE TITLE
Deployed Contracts On Kovan Test Net Not Loading

### ISSUE THREAD

**Issue by GitHubPete** [poanetwork/ico-wizard#515]
Hello,
When I visit https://wizard.oracles.org/ and click on 'Choose Contract' button, my contracts do not load.
I have already created a couple of them and the load was working properly until today (25.1.2018)
I do not have any output in dev console.
Thanks

**Comment by vbaranov** [comment]
Hi, 
- is unlocked account in MetaMask the same, that you have used for contracts creation?
- are you connected to the same blockchain, where you've created contracts?

**Comment by GitHubPete** [comment]
Hi Victor,
Yes, unlocked account is MetaMask is the same and I am connected to Kovan Test Net where contracts have been created.

**Comment by vbaranov** [comment]
Log with an error from Kovan:
[wizard.poa.network-1516881446330.log](https://github.com/poanetwork/ico-wizard/files/1663832/wizard.poa.network-1516881446330.log)
@fernandomg @fvictorio could you take a look?

**Comment by fvictorio** [comment]
I feel like this is a problem with MetaMask. See https://github.com/MetaMask/metamask-extension/issues/3095

**Comment by fvictorio** [comment]
Indeed, tried with a previous version of MetaMask and it worked, so the problem is there almost for sure.
